pipeline {
    agent any
    stages {    
        stage('Build Jar') {
            steps {
            	sh 'cd ${WORKSPACE}/TestDockerisation'
            	sh'pwd'
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Build Image') {
            steps {
                script {
                		//  pnarah/testrepo docker container repository name
                      app = docker.build("pnarah/testrepo")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                	// dockerhub - create Jenkin credential with this id 
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }        
    }
}