pipeline {
    agent none
    stages {    
        stage('Build Jar') {
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Build Image') {
            steps {
                script {
                		//  pnarah/testrepo docker container repository name
                      app = docker.build("pnarah/testrepo")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
                	// dockerhub - create Jenkin credential with this id 
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }        
    }
}